DROP TABLE IF EXISTS `T_LEAF_ALLOC`;

CREATE TABLE `T_LEAF_ALLOC` (
  `BIZ_TAG` varchar(128)  NOT NULL DEFAULT '',
  `MAX_ID` bigint(20) NOT NULL DEFAULT '1',
  `STEP` int(11) NOT NULL,
  `DESCRIPTION` varchar(256)  DEFAULT NULL,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`BIZ_TAG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
